 
 


// Generated helper templates
// CarbonKnown.MVC\CarbonKnown.MVC\Controllers\Services.txt4
// CarbonKnown.MVC\CarbonKnown.MVC\App_Start\Services.txt4
// CarbonKnown.MVC\CarbonKnown.WCF\Water\Services.txt4
// CarbonKnown.MVC\CarbonKnown.MVC\Service\Services.txt4
// CarbonKnown.MVC\CarbonKnown.WCF\Waste\Services.txt4
// CarbonKnown.MVC\CarbonKnown.WCF\Fleet\Services.txt4
// CarbonKnown.MVC\CarbonKnown.WCF\Refrigerant\Services.txt4
// CarbonKnown.MVC\CarbonKnown.WCF\Paper\Services.txt4
// CarbonKnown.MVC\CarbonKnown.WCF\Fuel\Services.txt4
// CarbonKnown.MVC\CarbonKnown.WCF\Electricity\Services.txt4
// CarbonKnown.MVC\CarbonKnown.WCF\Courier\Services.txt4
// CarbonKnown.MVC\CarbonKnown.WCF\CourierRoute\Services.txt4
// CarbonKnown.MVC\CarbonKnown.WCF\Commuting\Services.txt4
// CarbonKnown.MVC\CarbonKnown.WCF\CarHire\Services.txt4
// CarbonKnown.MVC\CarbonKnown.WCF\AirTravel\Services.txt4
// CarbonKnown.MVC\CarbonKnown.WCF\AirTravelRoute\Services.txt4
// CarbonKnown.MVC\CarbonKnown.WCF\Accommodation\Services.txt4
// Generated items
// CarbonKnown.MVC\CarbonKnown.MVC\Controllers\DataSourceControllerExt.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Controllers\EditSourceControllerExt.cs
// CarbonKnown.MVC\CarbonKnown.MVC\App_Start\BootstrapperExt.cs
// CarbonKnown.MVC\CarbonKnown.WCF\Water\IWaterService.cs
// CarbonKnown.MVC\CarbonKnown.WCF\Water\WaterDataContract.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\Water.svc.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\Water.svc
// CarbonKnown.MVC\CarbonKnown.WCF\Waste\IWasteService.cs
// CarbonKnown.MVC\CarbonKnown.WCF\Waste\WasteType.cs
// CarbonKnown.MVC\CarbonKnown.WCF\Waste\WasteDataContract.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\Waste.svc.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\Waste.svc
// CarbonKnown.MVC\CarbonKnown.WCF\Fleet\IFleetService.cs
// CarbonKnown.MVC\CarbonKnown.WCF\Fleet\FuelType.cs
// CarbonKnown.MVC\CarbonKnown.WCF\Fleet\FleetScope.cs
// CarbonKnown.MVC\CarbonKnown.WCF\Fleet\FleetDataContract.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\Fleet.svc.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\Fleet.svc
// CarbonKnown.MVC\CarbonKnown.WCF\Refrigerant\IRefrigerantService.cs
// CarbonKnown.MVC\CarbonKnown.WCF\Refrigerant\RefrigerantType.cs
// CarbonKnown.MVC\CarbonKnown.WCF\Refrigerant\RefrigerantDataContract.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\Refrigerant.svc.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\Refrigerant.svc
// CarbonKnown.MVC\CarbonKnown.WCF\Paper\IPaperService.cs
// CarbonKnown.MVC\CarbonKnown.WCF\Paper\PaperUom.cs
// CarbonKnown.MVC\CarbonKnown.WCF\Paper\PaperType.cs
// CarbonKnown.MVC\CarbonKnown.WCF\Paper\PaperDataContract.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\Paper.svc.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\Paper.svc
// CarbonKnown.MVC\CarbonKnown.WCF\Fuel\IFuelService.cs
// CarbonKnown.MVC\CarbonKnown.WCF\Fuel\UnitOfMeasure.cs
// CarbonKnown.MVC\CarbonKnown.WCF\Fuel\FuelType.cs
// CarbonKnown.MVC\CarbonKnown.WCF\Fuel\FuelDataContract.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\Fuel.svc.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\Fuel.svc
// CarbonKnown.MVC\CarbonKnown.WCF\Electricity\IElectricityService.cs
// CarbonKnown.MVC\CarbonKnown.WCF\Electricity\ElectricityType.cs
// CarbonKnown.MVC\CarbonKnown.WCF\Electricity\ElectricityDataContract.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\Electricity.svc.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\Electricity.svc
// CarbonKnown.MVC\CarbonKnown.WCF\Courier\ICourierService.cs
// CarbonKnown.MVC\CarbonKnown.WCF\Courier\ServiceType.cs
// CarbonKnown.MVC\CarbonKnown.WCF\Courier\CourierDataContract.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\Courier.svc.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\Courier.svc
// CarbonKnown.MVC\CarbonKnown.WCF\CourierRoute\ICourierRouteService.cs
// CarbonKnown.MVC\CarbonKnown.WCF\CourierRoute\ServiceType.cs
// CarbonKnown.MVC\CarbonKnown.WCF\CourierRoute\CourierRouteDataContract.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\CourierRoute.svc.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\CourierRoute.svc
// CarbonKnown.MVC\CarbonKnown.WCF\Commuting\ICommutingService.cs
// CarbonKnown.MVC\CarbonKnown.WCF\Commuting\CommutingType.cs
// CarbonKnown.MVC\CarbonKnown.WCF\Commuting\CommutingDataContract.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\Commuting.svc.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\Commuting.svc
// CarbonKnown.MVC\CarbonKnown.WCF\CarHire\ICarHireService.cs
// CarbonKnown.MVC\CarbonKnown.WCF\CarHire\CarGroupBill.cs
// CarbonKnown.MVC\CarbonKnown.WCF\CarHire\CarHireDataContract.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\CarHire.svc.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\CarHire.svc
// CarbonKnown.MVC\CarbonKnown.WCF\AirTravel\IAirTravelService.cs
// CarbonKnown.MVC\CarbonKnown.WCF\AirTravel\TravelClass.cs
// CarbonKnown.MVC\CarbonKnown.WCF\AirTravel\AirTravelDataContract.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\AirTravel.svc.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\AirTravel.svc
// CarbonKnown.MVC\CarbonKnown.WCF\AirTravelRoute\IAirTravelRouteService.cs
// CarbonKnown.MVC\CarbonKnown.WCF\AirTravelRoute\TravelClass.cs
// CarbonKnown.MVC\CarbonKnown.WCF\AirTravelRoute\AirTravelRouteDataContract.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\AirTravelRoute.svc.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\AirTravelRoute.svc
// CarbonKnown.MVC\CarbonKnown.WCF\Accommodation\IAccommodationService.cs
// CarbonKnown.MVC\CarbonKnown.WCF\Accommodation\AccommodationDataContract.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\Accommodation.svc.cs
// CarbonKnown.MVC\CarbonKnown.MVC\Service\Accommodation.svc
