//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarbonKnown.Calculation.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarbonKnown.Calculation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has exceeded the variance value of {1:0.00}.
        /// </summary>
        public static string AboveVarianceMaxMessage {
            get {
                return ResourceManager.GetString("AboveVarianceMaxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is below the variance value of {1:0.00}.
        /// </summary>
        public static string BelowVarianceMinMessage {
            get {
                return ResourceManager.GetString("BelowVarianceMinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error occured while trying to calculate the carbon emissions correlation id: {{{0}}}.
        /// </summary>
        public static string CalculationError {
            get {
                return ResourceManager.GetString("CalculationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This entry is a possible duplicate.
        /// </summary>
        public static string DuplicateMessage {
            get {
                return ResourceManager.GetString("DuplicateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The factor value for {0} for calculation date {1} was not found.
        /// </summary>
        public static string FactorValueNotFound {
            get {
                return ResourceManager.GetString("FactorValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cost Code is invalid.
        /// </summary>
        public static string InvalidCostCodeMessage {
            get {
                return ResourceManager.GetString("InvalidCostCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for {0} is invalid.
        /// </summary>
        public static string MissingValueMessage {
            get {
                return ResourceManager.GetString("MissingValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Distance for the route from {0} to {1} could not be calculated..
        /// </summary>
        public static string RouteDistanceMissing {
            get {
                return ResourceManager.GetString("RouteDistanceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start date is greater than the end date.
        /// </summary>
        public static string StartDateGreaterThanEndDateMessage {
            get {
                return ResourceManager.GetString("StartDateGreaterThanEndDateMessage", resourceCulture);
            }
        }
    }
}
